"use-client"
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/slices/store";
export const metadata = {
  title: "Music player",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">{children}</html>
    </Provider>
  );
}
