import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/x-icon"  href="./favicon.ico" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
